baseURL = "https://agcl.cn"
languageCode = 'zh-cn'
title = "Thoughts on AgCl"

theme = "yinyang"

[params]
headTitle = "AgCl"
mainSections = ["posts"]
description = "AgCl's personal blog, sharing thoughts and experiences on technology, programming, and life."

[[params.socials]]
name = "About Me"
link = "https://agcl.cn/about/"
[[params.socials]]
name = "Github"
link = "https://github.com/hongyan02"

[[params.socials]]
name = "RSS"
link = "/index.xml"

[permalinks]
page = "/:title/"
posts = "/blog/:title/"
